works

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,6 +1,5 @@
 # Use the official Node.js image as the base image
 FROM node:18-alpine AS base
-RUN npm install -g pnpm
 
 # Install Rust and wasm-pack
 FROM base AS rust-builder
@@ -15,40 +14,69 @@ WORKDIR /app
 COPY wasm ./wasm
 RUN cd wasm && wasm-pack build --target web
 
-
-# Build Next.js app
-FROM base AS builder
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json pnpm-lock.yaml ./
-# Install the dependencies
-RUN pnpm install
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY --from=wasm-builder /app/wasm/pkg ./wasm/pkg
 
 COPY . .
-COPY --from=wasm-builder /app/wasm/pkg ./wasm/pkg
-RUN pnpm run prisma:generate
-RUN pnpm run build
+ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run prisma:generate && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # Production image
 FROM base AS runner
 WORKDIR /app
-
-ENV NODE_ENV production
+RUN npm install -g pnpm
+ENV NODE_ENV=production
+ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder --chown=nextjs:nodejs /app/public ./
-COPY --from=builder --chown=nextjs:nodejs /app/prisma ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next ./
-COPY --from=builder --chown=nextjs:nodejs /app/wasm/pkg ./wasm/pkg
+COPY --from=builder /app/public ./public
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
+COPY --from=deps /app/node_modules ./node_modules
+COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
+COPY --from=builder --chown=nextjs:nodejs /app/package.json ./
 
 COPY --chown=nextjs:nextjs --chmod=744 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
+
+RUN pnpm run prisma:generate
 USER nextjs
 
 # Expose port 3000 to the outside world
 EXPOSE 3000
 
+ENV PORT=3000
+
 ENTRYPOINT [ "docker-entrypoint.sh" ]
-# Start the application
-CMD ["pnpm", "start"]
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
+CMD ["pnpm", "run", "start"]
